<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SubGrupoCategoriasRequisitosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $requisitos_categoria = [
            //hoteles
            //hotel
            //5 estrellas
            'CARACTERÍSTICAS GENERALES' => 1,
            'EXTERIORES' => 2,
            'INTERIORES' => 3,
            'UNIDADES HABITACIONALES' => 4,
            'UNIDADES COMPLEMENTARIAS' => 5,
            'SEÑALETICA' => 6,
            //hotel 4 estrellas
            'CARACTERÍSTICAS GENERALES' => 7,
            'EXTERIORES' => 8,
            'INTERIORES' => 9,
            'UNIDADES HABITACIONALES' => 10,
            'UNIDADES COMPLEMENTARIAS' => 11,
            'SEÑALETICA' => 12,
            //hotel 3 estrellas
            'CARACTERÍSTICAS GENERALES' => 13,
            'EXTERIORES' => 14,
            'INTERIORES' => 15,
            'UNIDADES HABITACIONALES' => 16,
            'UNIDADES COMPLEMENTARIAS' => 17,
            'SEÑALETICA' => 18,
            //hotel 2 estrellas
            'CARACTERÍSTICAS GENERALES' => 19,
            'EXTERIORES' => 20,
            'INTERIORES' => 21,
            'UNIDADES HABITACIONALES' => 22,
            'UNIDADES COMPLEMENTARIAS' => 23,
            'SEÑALETICA' => 24,
            //hotel 1 estrella
            'CARACTERÍSTICAS GENERALES' => 25,
            'EXTERIORES' => 26,
            'INTERIORES' => 27,
            'UNIDADES HABITACIONALES' => 28,
            'UNIDADES COMPLEMENTARIAS' => 29,
            'SEÑALETICA' => 30,
            //
            'CARACTERÍSTICAS GENERALES' => 31,
            'EXTERIORES' => 32,
            'INTERIORES' => 33,
            'UNIDADES HABITACIONALES' => 34,
            'UNIDADES COMPLEMENTARIAS' => 35,
            'SEÑALETICA' => 36,
            'CARACTERÍSTICAS GENERALES' => 37,
            'EXTERIORES' => 38,
            'INTERIORES' => 39,
            'UNIDADES HABITACIONALES' => 40,
            'UNIDADES COMPLEMENTARIAS' => 41,
            'SEÑALETICA' => 42,
            'CARACTERÍSTICAS GENERALES' => 43,
            'EXTERIORES' => 44,
            'INTERIORES' => 45,
            'UNIDADES HABITACIONALES' => 46,
            'UNIDADES COMPLEMENTARIAS' => 47,
            'SEÑALETICA' => 48,
            'CARACTERÍSTICAS GENERALES' => 49,
            'EXTERIORES' => 50,
            'INTERIORES' => 51,
            'UNIDADES HABITACIONALES' => 52,
            'UNIDADES COMPLEMENTARIAS' => 53,
            'SEÑALETICA' => 54,
            'CARACTERÍSTICAS GENERALES' => 55,
            'EXTERIORES' => 56,
            'INTERIORES' => 57,
            'UNIDADES HABITACIONALES' => 58,
            'UNIDADES COMPLEMENTARIAS' => 59,
            'SEÑALETICA' => 60,
            'CARACTERÍSTICAS GENERALES' => 61,
            'EXTERIORES' => 62,
            'INTERIORES' => 63,
            'UNIDADES HABITACIONALES' => 64,
            'SEÑALETICA' => 65,
            'CARACTERÍSTICAS GENERALES' => 66,
            'EXTERIORES' => 67,
            'INTERIORES' => 68,
            'UNIDADES HABITACIONALES' => 69,
            'SEÑALETICA' => 70,
            'CARACTERÍSTICAS GENERALES' => 71,
            'EXTERIORES' => 72,
            'INTERIORES' => 73,
            'UNIDADES HABITACIONALES' => 74,
            'SEÑALETICA' => 75,
            'CARACTERÍSTICAS GENERALES' => 76,
            'EXTERIORES' => 77,
            'INTERIORES' => 78,
            'UNIDADES HABITACIONALES' => 79,
            'SEÑALETICA' => 80,
            'CARACTERÍSTICAS GENERALES' => 81,
            'EXTERIORES' => 82,
            'INTERIORES' => 83,
            'UNIDADES HABITACIONALES' => 84,
            'SEÑALETICA' => 85,
            'CARACTERÍSTICAS GENERALES' => 86,
            'EXTERIORES' => 87,
            'INTERIORES' => 88,
            'UNIDADES HABITACIONALES' => 89,
            'SEÑALETICA' => 90,
            'CARACTERÍSTICAS GENERALES' => 91,
            'EXTERIORES' => 92,
            'INTERIORES' => 93,
            'UNIDADES HABITACIONALES' => 94,
            'SEÑALETICA' => 95,
            'CARACTERÍSTICAS GENERALES' => 96,
            'EXTERIORES' => 97,
            'INTERIORES' => 98,
            'UNIDADES HABITACIONALES' => 99,
            'SEÑALETICA' => 100,
            'CARACTERÍSTICAS GENERALES' => 101,
            'EXTERIORES' => 102,
            'INTERIORES' => 103,
            'UNIDADES HABITACIONALES' => 104,
            'SEÑALETICA' => 105,
            'CARACTERÍSTICAS GENERALES' => 106,
            'EXTERIORES' => 107,
            'INTERIORES' => 108,
            'UNIDADES HABITACIONALES' => 109,
            'SEÑALETICA' => 110,
            'CARACTERÍSTICAS GENERALES' => 111,
            'EXTERIORES' => 112,
            'INTERIORES' => 113,
            'UNIDADES HABITACIONALES' => 114,
            'SEÑALETICA' => 115,
            'CARACTERÍSTICAS GENERALES' => 116,
            'EXTERIORES' => 117,
            'INTERIORES' => 118,
            'SEÑALETICA' => 119,
            'CARACTERÍSTICAS GENERALES' => 120,
            'CARACTERÍSTICAS GENERALES' => 121,
            'CARACTERÍSTICAS GENERALES' => 122,
            'CARACTERÍSTICAS GENERALES' => 123,
            'CARACTERÍSTICAS GENERALES' => 124,
            'CARACTERÍSTICAS GENERALES' => 125,
            'CARACTERÍSTICAS GENERALES' => 126,
            'CARACTERÍSTICAS GENERALES' => 127,
            'CARACTERÍSTICAS GENERALES' => 128,
            'CARACTERÍSTICAS GENERALES' => 129,
            'CARACTERÍSTICAS GENERALES' => 130,
            'CARACTERÍSTICAS GENERALES' => 131,
            'CARACTERÍSTICAS GENERALES' => 132,
            'CARACTERÍSTICAS GENERALES' => 133,
            'CARACTERÍSTICAS GENERALES' => 134,
            'INFRAESTRUCTURA Y EQUIPAMIENTO' => 135,
            'SERVICIOS' => 136,
            'ÁREA DEL ESTABLECIMIENTO BASICO' => 137,
            'CARACTERÍSTICAS GENERALES' => 138,
            'INFRAESTRUCTURA Y EQUIPAMIENTO' => 139,
            'SERVICIOS' => 140,
            'ÁREA DEL ESTABLECIMIENTO BASICO' => 141,
            'CARACTERÍSTICAS GENERALES' => 142,
            'INFRAESTRUCTURA Y EQUIPAMIENTO' => 143,
            'SERVICIOS' => 144,
            'ÁREA DEL ESTABLECIMIENTO BASICO' => 145,
            'CARACTERÍSTICAS GENERALES' => 146,
            'INFRAESTRUCTURA Y EQUIPAMIENTO' => 147,
            'SERVICIOS' => 148,
            'ÁREA DEL ESTABLECIMIENTO BASICO' => 149,
            'CARACTERÍSTICAS GENERALES' => 150,
            'INFRAESTRUCTURA Y EQUIPAMIENTO' => 151,
            'SERVICIOS' => 152,
            'ÁREA DEL ESTABLECIMIENTO BASICO' => 153,
            'CARACTERÍSTICAS GENERALES' => 154,
            'CARACTERÍSTICAS GENERALES' => 155,
            'CARACTERÍSTICAS GENERALES' => 156,
            'CARACTERÍSTICAS GENERALES' => 157,
        ];
        $sub_grupo = [
             //5 estrellas
            [
                'nombre'=> 'Unidades Habitacionales',
                'requisito_categoria_id' =>1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'Instalaciones Recreacionales',
                'requisito_categoria_id' =>1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'Áreas Comunes',
                'requisito_categoria_id' =>1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'Áreas y servicios en exteriores',
                'requisito_categoria_id' =>1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'Unidades Complementarias',
                'requisito_categoria_id' =>1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'Otras condiciones generales',
                'requisito_categoria_id' =>1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            //------------------------------------------------
            [
                'nombre'=> 'CARACTERISTICAS DE INFRAESTRUCTURA',
                'requisito_categoria_id' =>2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'CARACTERÍSTICAS DE EQUIPAMIENTO',
                'requisito_categoria_id' =>2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'CARACTERÍSTICAS DE SERVICIO',
                'requisito_categoria_id' =>2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            //===================================================
            [
                'nombre'=> 'ÁREAS COMUNES',
                'requisito_categoria_id' =>3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'CARACTERISTICAS DE INFRAESTRUCTURA',
                'requisito_categoria_id' =>3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'CARACTERÍSTICAS DE EQUIPAMIENTO',
                'requisito_categoria_id' =>3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'CARACTERÍSTICAS DEL PERSONAL DE SERVICIO',
                'requisito_categoria_id' =>3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'RECEPCIÓN Y CONSERJERÍA',
                'requisito_categoria_id' =>3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'CARACTERISTICAS DE INFRAESTRUCTURA',
                'requisito_categoria_id' =>3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'CARACTERÍSTICAS DE EQUIPAMIENTO',
                'requisito_categoria_id' =>3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'CARACTERÍSTICAS DE SERVICIO',
                'requisito_categoria_id' =>3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'DEPENDENCIAS PARA EL PERSONAL',
                'requisito_categoria_id' =>3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'CARACTERISTICAS DE INFRAESTRUCTURA',
                'requisito_categoria_id' =>3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'CARACTERÍSTICAS DE EQUIPAMIENTO',
                'requisito_categoria_id' =>3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'ALIMENTOS Y BEBIDAS',
                'requisito_categoria_id' =>3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'CARACTERISTICAS DE INFRAESTRUCTURA',
                'requisito_categoria_id' =>3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'CARACTERÍSTICAS DE EQUIPAMIENTO',
                'requisito_categoria_id' =>3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'CARACTERÍSTICAS DE SERVICIO',
                'requisito_categoria_id' =>3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'ÁREAS DE MANTENIMIENTO',
                'requisito_categoria_id' =>3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'CARACTERISTICAS DE INFRAESTRUCTURA',
                'requisito_categoria_id' =>3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'CARACTERÍSTICAS DE EQUIPAMIENTO',
                'requisito_categoria_id' =>3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'LAVANDERÍA',
                'requisito_categoria_id' =>3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'CARACTERISTICAS DE INFRAESTRUCTURA',
                'requisito_categoria_id' =>3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'CARACTERÍSTICAS DE EQUIPAMIENTO',
                'requisito_categoria_id' =>3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'CARACTERÍSTICAS DE SERVICIO',
                'requisito_categoria_id' =>3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nombre'=> 'ACCESO Y CIRCULACIÓN',
                'requisito_categoria_id' =>3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];
    }
}
